name: Build
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        java: [21]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'oracle'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          validate-wrappers: true
      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew build
      - name: Capture Artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == 21 }}
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
